### ISSUE TITLE
No RSS

### ISSUE THREAD

**Issue by dannyfritz** [w3cj/null.computer#1]
You should add an RSS or Atom feed to so I can more easily spy on you. 🕵️ 

Also found this other similarly named blog when searching: http://nullprogram.com/blog/2013/09/23/

**Comment by w3cj** [comment]
🤘 Thanks for the tip! I was thinking of writing a few scripts to auto generate the posts locally for SEO, I should add one for RSS too. I just don't want this to turn into something like jekyll...

**Comment by w3cj** [comment]
For now there is this: https://github.com/w3cj/null.computer/commits/master.atom
But I will definitely work on one that has post titles and contents

**Comment by w3cj** [comment]
I done done it.

http://null.computer/feed.rss
http://null.computer/feed.atom

**Comment by dannyfritz** [comment]
So awesome. 📡 

![chrome_2017-01-01_18-48-15](https://cloud.githubusercontent.com/assets/315788/21583952/fb57a574-d052-11e6-8dde-ff12da43c6f1.png)

**Comment by w3cj** [comment]
Hope my latest feed updates don't mess things up too bad... the git log parser I was using didn't work the way I expected and all the posts had the wrong created/updated dates. The dates are correct now, but not sure how this will affect your feed reader.

**Comment by dannyfritz** [comment]
Only one new story showed up for `RSS/Atom Feed Generator`. Feed readers usually only care about `id` and Feedly might also be smart enough to only pull in stories dated since the last check.
